
[functions.mayar-saas-checkout]
enabled = true
verify_jwt = true
import_map = "./functions/mayar-saas-checkout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mayar-saas-checkout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mayar-saas-checkout/*.html" ]

[functions.mayar-saas-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/mayar-saas-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mayar-saas-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mayar-saas-webhook/*.html" ]
